### ISSUE TITLE
Use of caching library

### ISSUE THREAD

**Issue by dgomes** [pypolestar/pypolestar#1]
Was working on a similar refactor :)

Might I propose the use of an external caching library ? e.g. https://github.com/karpetrosyan/hishel

We should use httpx instead of aiohttp as polestar servers already support HTTP2

**Comment by leeyuentuen** [comment]
i think my problem now is not the src code. but the action to publish to pypi. i think somewhere i done something wrong

**Comment by dgomes** [comment]
the "release" job is already publishing to pipy although the version is hardcoded into pyproject.toml

Are you in Home Assistant Discord ? I go by the same handle as here

**Comment by jschlyter** [comment]
Latest code imported, is this still relevant @dgomes ?

**Comment by dgomes** [comment]
Thank you @jschlyter
