### ISSUE TITLE
Transfer PyPi project

### ISSUE THREAD

**Issue by jschlyter** [pypolestar/pypolestar#10]
Please add me as owner for https://pypi.org/project/pypolestar/ via https://pypi.org/manage/project/pypolestar/collaboration/ so I can publish an updated version of the library.

**Comment by jschlyter** [comment]
Ping @leeyuentuen

**Comment by leeyuentuen** [comment]
Invited

**Comment by jschlyter** [comment]
I need to be owner in order to configure the project.

**Comment by leeyuentuen** [comment]
> I need to be owner in order to configure the project.

Done
